package com.example.demo.model;
// Generated Sep 19, 2026, 8:47:36 AM by Hibernate Tools 6.6.1.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

/**
 * Employees generated by hbm2java
 */
@Entity
@Table(name="employees"
)
public class Employees  implements java.io.Serializable {


     private int employeenumber;
     private Employees employees;
     private Offices offices;
     private String lastname;
     private String firstname;
     private String extension;
     private String email;
     private String jobtitle;
     private Set<Customers> customerses = new HashSet<Customers>(0);
     private Set<Employees> employeeses = new HashSet<Employees>(0);

    public Employees() {
    }

	
    public Employees(int employeenumber, Offices offices, String lastname, String firstname, String extension, String email, String jobtitle) {
        this.employeenumber = employeenumber;
        this.offices = offices;
        this.lastname = lastname;
        this.firstname = firstname;
        this.extension = extension;
        this.email = email;
        this.jobtitle = jobtitle;
    }
    public Employees(int employeenumber, Employees employees, Offices offices, String lastname, String firstname, String extension, String email, String jobtitle, Set<Customers> customerses, Set<Employees> employeeses) {
       this.employeenumber = employeenumber;
       this.employees = employees;
       this.offices = offices;
       this.lastname = lastname;
       this.firstname = firstname;
       this.extension = extension;
       this.email = email;
       this.jobtitle = jobtitle;
       this.customerses = customerses;
       this.employeeses = employeeses;
    }
   
     @Id 

    
    @Column(name="employeenumber", unique=true, nullable=false)
    public int getEmployeenumber() {
        return this.employeenumber;
    }
    
    public void setEmployeenumber(int employeenumber) {
        this.employeenumber = employeenumber;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="reportsto")
    public Employees getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Employees employees) {
        this.employees = employees;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="officecode", nullable=false)
    public Offices getOffices() {
        return this.offices;
    }
    
    public void setOffices(Offices offices) {
        this.offices = offices;
    }

    
    @Column(name="lastname", nullable=false, length=50)
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    
    @Column(name="firstname", nullable=false, length=50)
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    
    @Column(name="extension", nullable=false, length=10)
    public String getExtension() {
        return this.extension;
    }
    
    public void setExtension(String extension) {
        this.extension = extension;
    }

    
    @Column(name="email", nullable=false, length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="jobtitle", nullable=false, length=50)
    public String getJobtitle() {
        return this.jobtitle;
    }
    
    public void setJobtitle(String jobtitle) {
        this.jobtitle = jobtitle;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="employees")
    public Set<Customers> getCustomerses() {
        return this.customerses;
    }
    
    public void setCustomerses(Set<Customers> customerses) {
        this.customerses = customerses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="employees")
    public Set<Employees> getEmployeeses() {
        return this.employeeses;
    }
    
    public void setEmployeeses(Set<Employees> employeeses) {
        this.employeeses = employeeses;
    }




}


