package com.example.demo.model;
// Generated Sep 19, 2026, 8:47:36 AM by Hibernate Tools 6.6.1.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import org.locationtech.jts.geom.Geometry;

/**
 * Offices generated by hbm2java
 */
@Entity
@Table(name="offices"
)
public class Offices  implements java.io.Serializable {


     private String officecode;
     private String city;
     private String phone;
     private String addressline1;
     private String addressline2;
     private String state;
     private String country;
     private String postalcode;
     private String territory;
     private Geometry officelocation;
     private Set<Employees> employeeses = new HashSet<Employees>(0);

    public Offices() {
    }

	
    public Offices(String officecode, String city, String phone, String addressline1, String country, String postalcode, String territory, Geometry officelocation) {
        this.officecode = officecode;
        this.city = city;
        this.phone = phone;
        this.addressline1 = addressline1;
        this.country = country;
        this.postalcode = postalcode;
        this.territory = territory;
        this.officelocation = officelocation;
    }
    public Offices(String officecode, String city, String phone, String addressline1, String addressline2, String state, String country, String postalcode, String territory, Geometry officelocation, Set<Employees> employeeses) {
       this.officecode = officecode;
       this.city = city;
       this.phone = phone;
       this.addressline1 = addressline1;
       this.addressline2 = addressline2;
       this.state = state;
       this.country = country;
       this.postalcode = postalcode;
       this.territory = territory;
       this.officelocation = officelocation;
       this.employeeses = employeeses;
    }
   
     @Id 

    
    @Column(name="officecode", unique=true, nullable=false, length=10)
    public String getOfficecode() {
        return this.officecode;
    }
    
    public void setOfficecode(String officecode) {
        this.officecode = officecode;
    }

    
    @Column(name="city", nullable=false, length=50)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="phone", nullable=false, length=50)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="addressline1", nullable=false, length=50)
    public String getAddressline1() {
        return this.addressline1;
    }
    
    public void setAddressline1(String addressline1) {
        this.addressline1 = addressline1;
    }

    
    @Column(name="addressline2", length=50)
    public String getAddressline2() {
        return this.addressline2;
    }
    
    public void setAddressline2(String addressline2) {
        this.addressline2 = addressline2;
    }

    
    @Column(name="state", length=50)
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }

    
    @Column(name="country", nullable=false, length=50)
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }

    
    @Column(name="postalcode", nullable=false, length=15)
    public String getPostalcode() {
        return this.postalcode;
    }
    
    public void setPostalcode(String postalcode) {
        this.postalcode = postalcode;
    }

    
    @Column(name="territory", nullable=false, length=10)
    public String getTerritory() {
        return this.territory;
    }
    
    public void setTerritory(String territory) {
        this.territory = territory;
    }

    
    @Column(name="officelocation", nullable=false)
    public Geometry getOfficelocation() {
        return this.officelocation;
    }
    
    public void setOfficelocation(Geometry officelocation) {
        this.officelocation = officelocation;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="offices")
    public Set<Employees> getEmployeeses() {
        return this.employeeses;
    }
    
    public void setEmployeeses(Set<Employees> employeeses) {
        this.employeeses = employeeses;
    }




}


