package com.example.demo.model;
// Generated Sep 19, 2026, 8:47:36 AM by Hibernate Tools 6.6.1.Final


import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * Orderdetails generated by hbm2java
 */
@Entity
@Table(name="orderdetails"
)
public class Orderdetails  implements java.io.Serializable {


     private OrderdetailsId id;
     private Orders orders;
     private Products products;
     private int quantityordered;
     private java.math.BigDecimal priceeach;
     private short orderlinenumber;

    public Orderdetails() {
    }

    public Orderdetails(OrderdetailsId id, Orders orders, Products products, int quantityordered, java.math.BigDecimal priceeach, short orderlinenumber) {
       this.id = id;
       this.orders = orders;
       this.products = products;
       this.quantityordered = quantityordered;
       this.priceeach = priceeach;
       this.orderlinenumber = orderlinenumber;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="ordernumber", column=@Column(name="ordernumber", nullable=false) ), 
        @AttributeOverride(name="productcode", column=@Column(name="productcode", nullable=false, length=15) ) } )
    public OrderdetailsId getId() {
        return this.id;
    }
    
    public void setId(OrderdetailsId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ordernumber", nullable=false, insertable=false, updatable=false)
    public Orders getOrders() {
        return this.orders;
    }
    
    public void setOrders(Orders orders) {
        this.orders = orders;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="productcode", nullable=false, insertable=false, updatable=false)
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }

    
    @Column(name="quantityordered", nullable=false)
    public int getQuantityordered() {
        return this.quantityordered;
    }
    
    public void setQuantityordered(int quantityordered) {
        this.quantityordered = quantityordered;
    }

    
    @Column(name="priceeach", nullable=false, precision=10, scale=2)
    public java.math.BigDecimal getPriceeach() {
        return this.priceeach;
    }
    
    public void setPriceeach(java.math.BigDecimal priceeach) {
        this.priceeach = priceeach;
    }

    
    @Column(name="orderlinenumber", nullable=false)
    public short getOrderlinenumber() {
        return this.orderlinenumber;
    }
    
    public void setOrderlinenumber(short orderlinenumber) {
        this.orderlinenumber = orderlinenumber;
    }




}


