package com.example.demo.model;
// Generated Sep 19, 2026, 8:47:36 AM by Hibernate Tools 6.6.1.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Orders generated by hbm2java
 */
@Entity
@Table(name="orders"
)
public class Orders  implements java.io.Serializable {


     private int ordernumber;
     private Customers customers;
     private Timestamp orderdate;
     private Timestamp requireddate;
     private Timestamp shippeddate;
     private String status;
     private String comments;
     private Set<Orderdetails> orderdetailses = new HashSet<Orderdetails>(0);

    public Orders() {
    }

	
    public Orders(int ordernumber, Customers customers, Timestamp orderdate, Timestamp requireddate, String status) {
        this.ordernumber = ordernumber;
        this.customers = customers;
        this.orderdate = orderdate;
        this.requireddate = requireddate;
        this.status = status;
    }
    public Orders(int ordernumber, Customers customers, Timestamp orderdate, Timestamp requireddate, Timestamp shippeddate, String status, String comments, Set<Orderdetails> orderdetailses) {
       this.ordernumber = ordernumber;
       this.customers = customers;
       this.orderdate = orderdate;
       this.requireddate = requireddate;
       this.shippeddate = shippeddate;
       this.status = status;
       this.comments = comments;
       this.orderdetailses = orderdetailses;
    }
   
     @Id 

    
    @Column(name="ordernumber", unique=true, nullable=false)
    public int getOrdernumber() {
        return this.ordernumber;
    }
    
    public void setOrdernumber(int ordernumber) {
        this.ordernumber = ordernumber;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="customernumber", nullable=false)
    public Customers getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Customers customers) {
        this.customers = customers;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="orderdate", nullable=false, length=29)
    public Timestamp getOrderdate() {
        return this.orderdate;
    }
    
    public void setOrderdate(Timestamp orderdate) {
        this.orderdate = orderdate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="requireddate", nullable=false, length=29)
    public Timestamp getRequireddate() {
        return this.requireddate;
    }
    
    public void setRequireddate(Timestamp requireddate) {
        this.requireddate = requireddate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="shippeddate", length=29)
    public Timestamp getShippeddate() {
        return this.shippeddate;
    }
    
    public void setShippeddate(Timestamp shippeddate) {
        this.shippeddate = shippeddate;
    }

    
    @Column(name="status", nullable=false, length=15)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="comments")
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="orders")
    public Set<Orderdetails> getOrderdetailses() {
        return this.orderdetailses;
    }
    
    public void setOrderdetailses(Set<Orderdetails> orderdetailses) {
        this.orderdetailses = orderdetailses;
    }




}


