package com.example.demo.model;
// Generated Sep 18, 2026, 12:21:20 PM by Hibernate Tools 6.6.1.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import org.locationtech.jts.geom.Point;

/**
 * Customers generated by hbm2java
 */
@Entity
@Table(name = "customers")
public class Customers implements java.io.Serializable {

    private int customernumber;
    private Employees employees;
    private String customername;
    private String contactlastname;
    private String contactfirstname;
    private String phone;
    private String addressline1;
    private String addressline2;
    private String city;
    private String state;
    private String postalcode;
    private String country;
    private java.math.BigDecimal creditlimit;
    private Point customerlocation;
    private Set<Orders> orderses = new HashSet<Orders>(0);
    private Set<Payments> paymentses = new HashSet<Payments>(0);

    public Customers() {
    }

    public Customers(int customernumber, String customername, String contactlastname, String contactfirstname,
            String phone, String addressline1, String city, String country, org.locationtech.jts.geom.Point customerlocation) {
        this.customernumber = customernumber;
        this.customername = customername;
        this.contactlastname = contactlastname;
        this.contactfirstname = contactfirstname;
        this.phone = phone;
        this.addressline1 = addressline1;
        this.city = city;
        this.country = country;
        this.customerlocation = customerlocation;
    }

    public Customers(int customernumber, Employees employees, String customername, String contactlastname,
            String contactfirstname, String phone, String addressline1, String addressline2, String city, String state,
            String postalcode, String country, java.math.BigDecimal creditlimit, org.locationtech.jts.geom.Point customerlocation,
            Set<Orders> orderses, Set<Payments> paymentses) {
        this.customernumber = customernumber;
        this.employees = employees;
        this.customername = customername;
        this.contactlastname = contactlastname;
        this.contactfirstname = contactfirstname;
        this.phone = phone;
        this.addressline1 = addressline1;
        this.addressline2 = addressline2;
        this.city = city;
        this.state = state;
        this.postalcode = postalcode;
        this.country = country;
        this.creditlimit = creditlimit;
        this.customerlocation = customerlocation;
        this.orderses = orderses;
        this.paymentses = paymentses;
    }

    @Id

    @Column(name = "customernumber", unique = true, nullable = false)
    public int getCustomernumber() {
        return this.customernumber;
    }

    public void setCustomernumber(int customernumber) {
        this.customernumber = customernumber;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "salesrepemployeenumber")
    public Employees getEmployees() {
        return this.employees;
    }

    public void setEmployees(Employees employees) {
        this.employees = employees;
    }

    @Column(name = "customername", nullable = false, length = 50)
    public String getCustomername() {
        return this.customername;
    }

    public void setCustomername(String customername) {
        this.customername = customername;
    }

    @Column(name = "contactlastname", nullable = false, length = 50)
    public String getContactlastname() {
        return this.contactlastname;
    }

    public void setContactlastname(String contactlastname) {
        this.contactlastname = contactlastname;
    }

    @Column(name = "contactfirstname", nullable = false, length = 50)
    public String getContactfirstname() {
        return this.contactfirstname;
    }

    public void setContactfirstname(String contactfirstname) {
        this.contactfirstname = contactfirstname;
    }

    @Column(name = "phone", nullable = false, length = 50)
    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    @Column(name = "addressline1", nullable = false, length = 50)
    public String getAddressline1() {
        return this.addressline1;
    }

    public void setAddressline1(String addressline1) {
        this.addressline1 = addressline1;
    }

    @Column(name = "addressline2", length = 50)
    public String getAddressline2() {
        return this.addressline2;
    }

    public void setAddressline2(String addressline2) {
        this.addressline2 = addressline2;
    }

    @Column(name = "city", nullable = false, length = 50)
    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    @Column(name = "state", length = 50)
    public String getState() {
        return this.state;
    }

    public void setState(String state) {
        this.state = state;
    }

    @Column(name = "postalcode", length = 15)
    public String getPostalcode() {
        return this.postalcode;
    }

    public void setPostalcode(String postalcode) {
        this.postalcode = postalcode;
    }

    @Column(name = "country", nullable = false, length = 50)
    public String getCountry() {
        return this.country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    @Column(name = "creditlimit", precision = 10, scale = 2)
    public java.math.BigDecimal getCreditlimit() {
        return this.creditlimit;
    }

    public void setCreditlimit(java.math.BigDecimal creditlimit) {
        this.creditlimit = creditlimit;
    }

    // getter/setter:
    @Column(name = "customerlocation", nullable = false)
    public Point getCustomerlocation() {
        return this.customerlocation;
    }

    public void setCustomerlocation(Point customerlocation) {
        this.customerlocation = customerlocation;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "customers")
    public Set<Orders> getOrderses() {
        return this.orderses;
    }

    public void setOrderses(Set<Orders> orderses) {
        this.orderses = orderses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "customers")
    public Set<Payments> getPaymentses() {
        return this.paymentses;
    }

    public void setPaymentses(Set<Payments> paymentses) {
        this.paymentses = paymentses;
    }

}
