package com.example.demo.model;
// Generated Sep 18, 2026, 12:21:20 PM by Hibernate Tools 6.6.1.Final


import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * OrderdetailsId generated by hbm2java
 */
@Embeddable
public class OrderdetailsId  implements java.io.Serializable {


     private int ordernumber;
     private String productcode;

    public OrderdetailsId() {
    }

    public OrderdetailsId(int ordernumber, String productcode) {
       this.ordernumber = ordernumber;
       this.productcode = productcode;
    }
   


    @Column(name="ordernumber", nullable=false)
    public int getOrdernumber() {
        return this.ordernumber;
    }
    
    public void setOrdernumber(int ordernumber) {
        this.ordernumber = ordernumber;
    }


    @Column(name="productcode", nullable=false, length=15)
    public String getProductcode() {
        return this.productcode;
    }
    
    public void setProductcode(String productcode) {
        this.productcode = productcode;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OrderdetailsId) ) return false;
		 OrderdetailsId castOther = ( OrderdetailsId ) other; 
         
		 return (this.getOrdernumber()==castOther.getOrdernumber())
 && ( (this.getProductcode()==castOther.getProductcode()) || ( this.getProductcode()!=null && castOther.getProductcode()!=null && this.getProductcode().equals(castOther.getProductcode()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
        result = 37 * result + this.getOrdernumber();
        result = 37 * result + ( getProductcode() == null ? 0 : this.getProductcode().hashCode() );
         return result;
   }   


}


