package com.example.demo.model;
// Generated Sep 18, 2026, 12:21:20 PM by Hibernate Tools 6.6.1.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.sql.Timestamp;

/**
 * Payments generated by hbm2java
 */
@Entity
@Table(name="payments"
)
public class Payments  implements java.io.Serializable {


     private String checknumber;
     private Customers customers;
     private Timestamp paymentdate;
     private byte amount;

    public Payments() {
    }

    public Payments(String checknumber, Customers customers, Timestamp paymentdate, byte amount) {
       this.checknumber = checknumber;
       this.customers = customers;
       this.paymentdate = paymentdate;
       this.amount = amount;
    }
   
     @Id 

    
    @Column(name="checknumber", unique=true, nullable=false, length=50)
    public String getChecknumber() {
        return this.checknumber;
    }
    
    public void setChecknumber(String checknumber) {
        this.checknumber = checknumber;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="customernumber", nullable=false)
    public Customers getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Customers customers) {
        this.customers = customers;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="paymentdate", nullable=false, length=29)
    public Timestamp getPaymentdate() {
        return this.paymentdate;
    }
    
    public void setPaymentdate(Timestamp paymentdate) {
        this.paymentdate = paymentdate;
    }

    
    @Column(name="amount", nullable=false, precision=0, scale=0)
    public byte getAmount() {
        return this.amount;
    }
    
    public void setAmount(byte amount) {
        this.amount = amount;
    }




}


