package com.example.demo.model;
// Generated Sep 18, 2026, 12:21:20 PM by Hibernate Tools 6.6.1.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

/**
 * Productlines generated by hbm2java
 */
@Entity
@Table(name="productlines"
)
public class Productlines  implements java.io.Serializable {


     private String productline;
     private String textdescription;
     private String htmldescription;
     private byte[] image;
     private Set<Products> productses = new HashSet<Products>(0);

    public Productlines() {
    }

	
    public Productlines(String productline) {
        this.productline = productline;
    }
    public Productlines(String productline, String textdescription, String htmldescription, byte[] image, Set<Products> productses) {
       this.productline = productline;
       this.textdescription = textdescription;
       this.htmldescription = htmldescription;
       this.image = image;
       this.productses = productses;
    }
   
     @Id 

    
    @Column(name="productline", unique=true, nullable=false, length=50)
    public String getProductline() {
        return this.productline;
    }
    
    public void setProductline(String productline) {
        this.productline = productline;
    }

    
    @Column(name="textdescription", length=4000)
    public String getTextdescription() {
        return this.textdescription;
    }
    
    public void setTextdescription(String textdescription) {
        this.textdescription = textdescription;
    }

    
    @Column(name="htmldescription")
    public String getHtmldescription() {
        return this.htmldescription;
    }
    
    public void setHtmldescription(String htmldescription) {
        this.htmldescription = htmldescription;
    }

    
    @Column(name="image")
    public byte[] getImage() {
        return this.image;
    }
    
    public void setImage(byte[] image) {
        this.image = image;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="productlines")
    public Set<Products> getProductses() {
        return this.productses;
    }
    
    public void setProductses(Set<Products> productses) {
        this.productses = productses;
    }




}


