package com.example.demo.model;
// Generated Sep 18, 2026, 12:21:20 PM by Hibernate Tools 6.6.1.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

/**
 * Products generated by hbm2java
 */
@Entity
@Table(name="products"
)
public class Products  implements java.io.Serializable {


     private String productcode;
     private Productlines productlines;
     private String productname;
     private String productscale;
     private String productvendor;
     private String productdescription;
     private short quantityinstock;
     private byte buyprice;
     private byte msrp;
     private Set<Orderdetails> orderdetailses = new HashSet<Orderdetails>(0);

    public Products() {
    }

	
    public Products(String productcode, String productname, String productscale, String productvendor, String productdescription, short quantityinstock, byte buyprice, byte msrp) {
        this.productcode = productcode;
        this.productname = productname;
        this.productscale = productscale;
        this.productvendor = productvendor;
        this.productdescription = productdescription;
        this.quantityinstock = quantityinstock;
        this.buyprice = buyprice;
        this.msrp = msrp;
    }
    public Products(String productcode, Productlines productlines, String productname, String productscale, String productvendor, String productdescription, short quantityinstock, byte buyprice, byte msrp, Set<Orderdetails> orderdetailses) {
       this.productcode = productcode;
       this.productlines = productlines;
       this.productname = productname;
       this.productscale = productscale;
       this.productvendor = productvendor;
       this.productdescription = productdescription;
       this.quantityinstock = quantityinstock;
       this.buyprice = buyprice;
       this.msrp = msrp;
       this.orderdetailses = orderdetailses;
    }
   
     @Id 

    
    @Column(name="productcode", unique=true, nullable=false, length=15)
    public String getProductcode() {
        return this.productcode;
    }
    
    public void setProductcode(String productcode) {
        this.productcode = productcode;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="productline")
    public Productlines getProductlines() {
        return this.productlines;
    }
    
    public void setProductlines(Productlines productlines) {
        this.productlines = productlines;
    }

    
    @Column(name="productname", nullable=false, length=70)
    public String getProductname() {
        return this.productname;
    }
    
    public void setProductname(String productname) {
        this.productname = productname;
    }

    
    @Column(name="productscale", nullable=false, length=10)
    public String getProductscale() {
        return this.productscale;
    }
    
    public void setProductscale(String productscale) {
        this.productscale = productscale;
    }

    
    @Column(name="productvendor", nullable=false, length=50)
    public String getProductvendor() {
        return this.productvendor;
    }
    
    public void setProductvendor(String productvendor) {
        this.productvendor = productvendor;
    }

    
    @Column(name="productdescription", nullable=false)
    public String getProductdescription() {
        return this.productdescription;
    }
    
    public void setProductdescription(String productdescription) {
        this.productdescription = productdescription;
    }

    
    @Column(name="quantityinstock", nullable=false)
    public short getQuantityinstock() {
        return this.quantityinstock;
    }
    
    public void setQuantityinstock(short quantityinstock) {
        this.quantityinstock = quantityinstock;
    }

    
    @Column(name="buyprice", nullable=false, precision=0, scale=0)
    public byte getBuyprice() {
        return this.buyprice;
    }
    
    public void setBuyprice(byte buyprice) {
        this.buyprice = buyprice;
    }

    
    @Column(name="msrp", nullable=false, precision=0, scale=0)
    public byte getMsrp() {
        return this.msrp;
    }
    
    public void setMsrp(byte msrp) {
        this.msrp = msrp;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="products")
    public Set<Orderdetails> getOrderdetailses() {
        return this.orderdetailses;
    }
    
    public void setOrderdetailses(Set<Orderdetails> orderdetailses) {
        this.orderdetailses = orderdetailses;
    }




}


